"use client";

import { motion } from "framer-motion";
import {
  Brain,
  FileSearch,
  Rocket,
  MessageSquare,
  History,
  FolderKanban,
} from "lucide-react";

export default function BentoFeatures() {
  return (
    <section id="features" className="max-w-7xl mx-auto px-6 py-32">

      <motion.h2
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        className="text-center text-5xl font-bold"
      >
        Powerful AI Features
      </motion.h2>

      <p className="text-center text-[var(--pp-text-muted)] mt-5">
        Everything you need to crack your dream placement.
      </p>

      <div className="grid lg:grid-cols-3 gap-6 mt-20 auto-rows-[220px]">

        {/* Resume */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="lg:col-span-2 rounded-3xl bg-[var(--pp-panel)] border border-[var(--pp-line)] backdrop-blur-xl p-8 hover:border-purple-500 transition"
        >
          <Brain className="text-[var(--pp-ink)]" size={42} />

          <h3 className="mt-6 text-3xl font-bold">
            AI Resume Analysis
          </h3>

          <p className="mt-5 text-[var(--pp-text-muted)]">
            Upload your resume and receive ATS score,
            missing skills, strengths, weaknesses and
            AI recommendations within seconds.
          </p>
        </motion.div>

        {/* ATS */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="rounded-3xl bg-gradient-to-br from-purple-700 to-indigo-700 p-8"
        >
          <FileSearch size={38} />

          <h3 className="mt-5 text-2xl font-bold">
            ATS Score
          </h3>

          <div className="text-6xl mt-6 font-bold">
            95%
          </div>
        </motion.div>

        {/* Interview */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="rounded-3xl bg-[var(--pp-panel)] border border-[var(--pp-line)] backdrop-blur-xl p-8"
        >
          <MessageSquare className="text-[var(--pp-ink)]" size={38} />

          <h3 className="mt-5 text-2xl font-bold">
            Mock Interview
          </h3>

          <p className="text-[var(--pp-text-muted)] mt-4">
            AI-generated interview practice.
          </p>
        </motion.div>

        {/* Roadmap */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="lg:col-span-2 rounded-3xl bg-gradient-to-r from-[#141E30] to-[#243B55] p-8"
        >
          <Rocket className="text-orange-400" size={42} />

          <h3 className="mt-5 text-3xl font-bold">
            Personalized Career Roadmap
          </h3>

          <p className="mt-4 text-[var(--pp-text-muted)]">
            Weekly roadmap generated by AI based on
            your current skill level and dream company.
          </p>
        </motion.div>

        {/* Projects */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="lg:col-span-2 rounded-3xl bg-[var(--pp-panel)] border border-[var(--pp-line)] backdrop-blur-xl p-8"
        >
          <FolderKanban className="text-pink-400" size={38} />

          <h3 className="mt-5 text-2xl font-bold">
            AI Project Suggestions
          </h3>

          <p className="mt-4 text-[var(--pp-text-muted)]">
            Build resume-worthy projects recommended
            by AI according to your profile.
          </p>
        </motion.div>

        {/* History */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="rounded-3xl bg-[var(--pp-ink)] p-8"
        >
          <History size={38} />

          <h3 className="mt-5 text-2xl font-bold">
            History
          </h3>

          <p className="mt-4">
            Track every interview session.
          </p>
        </motion.div>

      </div>

    </section>
  );
}