"use client";

import { motion } from "framer-motion";
import {
  Brain,
  FileSearch,
  Rocket,
  MessageSquare,
  History,
  FolderKanban,
} from "lucide-react";

export default function BentoFeatures() {
  return (
    <section className="max-w-7xl mx-auto px-6 py-20 md:py-32">

      <motion.h2
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        className="text-center text-3xl sm:text-4xl md:text-5xl font-bold"
      >
        Powerful AI Features
      </motion.h2>

      <p className="text-center text-gray-600 mt-5">
        Everything you need to crack your dream placement.
      </p>

      <div className="grid lg:grid-cols-3 gap-6 mt-12 md:mt-20 auto-rows-auto lg:auto-rows-[220px]">

        {/* Resume */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="lg:col-span-2 rounded-3xl bg-orange-50 border border-orange-200 backdrop-blur-xl p-8 hover:border-orange-500 transition"
        >
          <Brain className="text-orange-600" size={42} />

          <h3 className="mt-6 text-3xl font-bold">
            AI Resume Analysis
          </h3>

          <p className="mt-5 text-gray-600">
            Upload your resume and receive ATS score,
            missing skills, strengths, weaknesses and
            AI recommendations within seconds.
          </p>
        </motion.div>

        {/* ATS */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="rounded-3xl bg-gradient-to-br from-orange-500 to-amber-600 p-8 text-white"
        >
          <FileSearch size={38} />

          <h3 className="mt-5 text-2xl font-bold">
            ATS Score
          </h3>

          <div className="text-5xl md:text-6xl mt-6 font-bold">
            95%
          </div>
        </motion.div>

        {/* Interview */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="rounded-3xl bg-orange-50 border border-orange-200 backdrop-blur-xl p-8"
        >
          <MessageSquare className="text-yellow-600" size={38} />

          <h3 className="mt-5 text-2xl font-bold">
            Mock Interview
          </h3>

          <p className="text-gray-600 mt-4">
            AI-generated interview practice.
          </p>
        </motion.div>

        {/* Roadmap */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="lg:col-span-2 rounded-3xl bg-gradient-to-r from-orange-500 to-amber-600 p-8 text-white"
        >
          <Rocket className="text-orange-600" size={42} />

          <h3 className="mt-5 text-3xl font-bold">
            Personalized Career Roadmap
          </h3>

          <p className="mt-4 text-gray-700">
            Weekly roadmap generated by AI based on
            your current skill level and dream company.
          </p>
        </motion.div>

        {/* Projects */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="lg:col-span-2 rounded-3xl bg-orange-50 border border-orange-200 backdrop-blur-xl p-8"
        >
          <FolderKanban className="text-amber-600" size={38} />

          <h3 className="mt-5 text-2xl font-bold">
            AI Project Suggestions
          </h3>

          <p className="mt-4 text-gray-600">
            Build resume-worthy projects recommended
            by AI according to your profile.
          </p>
        </motion.div>

        {/* History */}

        <motion.div
          whileHover={{ scale: 1.02 }}
          className="rounded-3xl bg-orange-600 p-8 text-white"
        >
          <History size={38} />

          <h3 className="mt-5 text-2xl font-bold">
            History
          </h3>

          <p className="mt-4">
            Track every interview session.
          </p>
        </motion.div>

      </div>

    </section>
  );
}